name: Branch Based CI CD
 
on:
  push:
    branches:
      - dev
      - main
 
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Build
      run: echo "Building application..."
 
    - name: Test
      run: |
        echo "Running tests..."
        cat app.txt
 
    - name: Deploy to DEV
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "CD for DEV branch"
        bash deploy/deploy-dev.sh
 
    - name: Deploy to PROD
      if: github.ref == 'refs/heads/main'
      run: |
        echo "CD for MAIN branch"
        bash deploy/deploy-prod.sh
